// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sangam.IdentityTenant.Infrastructure.Persistence;

#nullable disable

namespace Sangam.IdentityTenant.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityTenantDbContext))]
    [Migration("20260905155318_AddLoginOtp")]
    partial class AddLoginOtp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sangam.IdentityTenant.Domain.Authorization.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_key");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Key = "Tenant.Manage"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Key = "AdminUsers.Manage"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            Key = "Members.Read"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            Key = "Members.Write"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            Key = "Family.Write"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            Key = "Family.ApproveConversion"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000007"),
                            Key = "Timeline.Post"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000008"),
                            Key = "Timeline.Moderate"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000009"),
                            Key = "VolunteerGroups.Manage"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000a"),
                            Key = "Events.Publish"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000b"),
                            Key = "SocialIssues.Approve"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000c"),
                            Key = "CelebrityVoting.Configure"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000d"),
                            Key = "Pathshala.Manage"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000e"),
                            Key = "Pathshala.Attendance.Write"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000f"),
                            Key = "Pathshala.Exams.Write"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000010"),
                            Key = "Boli.Manage"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000011"),
                            Key = "Boli.PublishResults"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000012"),
                            Key = "Audit.Read"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000013"),
                            Key = "VolunteerGroups.Lead"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000014"),
                            Key = "Roles.Manage"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000015"),
                            Key = "Notifications.Broadcast"
                        });
                });

            modelBuilder.Entity("Sangam.IdentityTenant.Domain.Authorization.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "SamaajAdmin"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            Name = "Member"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Name = "FamilyHead"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            Name = "VolunteerGroupPresident"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            Name = "PathshalaTeacher"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            Name = "PathshalaStudent"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            Name = "ContentModerator"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000009"),
                            Name = "BoliManager"
                        });
                });

            modelBuilder.Entity("Sangam.IdentityTenant.Domain.Authorization.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-00000000000a")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-00000000000b")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-00000000000c")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-00000000000d")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-00000000000e")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-00000000000f")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-00000000000a")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-00000000000b")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-00000000000c")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-00000000000d")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000005"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-00000000000a")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-00000000000e")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000006"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-00000000000f")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000007"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000008"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000008"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000008"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-00000000000b")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000009"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000009"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000009"),
                            PermissionId = new Guid("b0000000-0000-0000-0000-000000000011")
                        });
                });

            modelBuilder.Entity("Sangam.IdentityTenant.Domain.Authorization.RolePermissionOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<bool>("Granted")
                        .HasColumnType("boolean")
                        .HasColumnName("granted");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_role_permission_overrides");

                    b.HasIndex("TenantId", "RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_role_permission_overrides_tenant_id_role_id_permission_id");

                    b.ToTable("role_permission_overrides", (string)null);
                });

            modelBuilder.Entity("Sangam.IdentityTenant.Domain.Authorization.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid?>("TenantScope")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_scope");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("UserId", "RoleId", "TenantScope")
                        .IsUnique()
                        .HasDatabaseName("ix_user_roles_user_id_role_id_tenant_scope");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Sangam.IdentityTenant.Domain.Consents.ConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<string>("NoticeVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("notice_version");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_consent_records");

                    b.HasIndex("UserId", "RecordedAt")
                        .HasDatabaseName("ix_consent_records_user_id_recorded_at");

                    b.ToTable("consent_records", (string)null);
                });

            modelBuilder.Entity("Sangam.IdentityTenant.Domain.Media.TenantLogo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ByteSize")
                        .HasColumnType("integer")
                        .HasColumnName("byte_size");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_tenant_logos");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_logos_tenant");

                    b.ToTable("tenant_logos", (string)null);
                });

            modelBuilder.Entity("Sangam.IdentityTenant.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_person");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<string>("GrievanceContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("grievance_contact_email");

                    b.Property<string>("GrievanceContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("grievance_contact_name");

                    b.Property<string>("GrievanceContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grievance_contact_phone");

                    b.Property<Guid?>("LogoImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("logo_image_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("_enabledModules")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("enabled_modules");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_domain")
                        .HasFilter("domain IS NOT NULL");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Sangam.IdentityTenant.Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("revoked_reason");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_refresh_tokens_session_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("ix_refresh_tokens_user_id_revoked_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Sangam.IdentityTenant.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("auth_method");

                    b.Property<Guid?>("ConvertedFromChildProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_from_child_profile_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsContactVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_contact_verified");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockedOutUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_out_until");

                    b.Property<string>("MobileOrEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("mobile_or_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("ConvertedFromChildProfileId")
                        .HasDatabaseName("ix_users_converted_from_child_profile_id");

                    b.HasIndex("MobileOrEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_mobile_or_email");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_users_tenant_id_status");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Sangam.IdentityTenant.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Sangam.IdentityTenant.Domain.Authorization.RolePermission", b =>
                {
                    b.HasOne("Sangam.IdentityTenant.Domain.Authorization.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("Sangam.IdentityTenant.Domain.Authorization.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");
                });

            modelBuilder.Entity("Sangam.IdentityTenant.Domain.Authorization.UserRole", b =>
                {
                    b.HasOne("Sangam.IdentityTenant.Domain.Authorization.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Sangam.IdentityTenant.Domain.Users.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Sangam.IdentityTenant.Domain.Users.User", b =>
                {
                    b.OwnsOne("Sangam.IdentityTenant.Domain.Users.ActivationCode", "ActivationCode", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("activation_code_expires_at");

                            b1.Property<int>("FailedAttempts")
                                .HasColumnType("integer")
                                .HasColumnName("activation_code_failed_attempts");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("activation_code_hash");

                            b1.Property<DateTimeOffset>("IssuedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("activation_code_issued_at");

                            b1.Property<Guid>("IssuedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("activation_code_issued_by");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.OwnsOne("Sangam.IdentityTenant.Domain.Users.LoginOtp", "LoginOtp", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("login_otp_expires_at");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("login_otp_hash");

                            b1.Property<DateTimeOffset>("IssuedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("login_otp_issued_at");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("ActivationCode");

                    b.Navigation("LoginOtp");
                });

            modelBuilder.Entity("Sangam.IdentityTenant.Domain.Users.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
