// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sangam.Timeline.Infrastructure.Persistence;

#nullable disable

namespace Sangam.Timeline.Infrastructure.Migrations
{
    [DbContext(typeof(TimelineDbContext))]
    [Migration("20260829002714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sangam.Timeline.Domain.Posts.ModerationAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_moderation_actions");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_moderation_actions_post_id");

                    b.ToTable("moderation_actions", (string)null);
                });

            modelBuilder.Entity("Sangam.Timeline.Domain.Posts.PostComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_member_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.HasKey("Id")
                        .HasName("pk_post_comments");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_comments_post_id");

                    b.ToTable("post_comments", (string)null);
                });

            modelBuilder.Entity("Sangam.Timeline.Domain.Posts.PostReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_post_reactions");

                    b.HasIndex("PostId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_post_reactions_post_id_member_id");

                    b.ToTable("post_reactions", (string)null);
                });

            modelBuilder.Entity("Sangam.Timeline.Domain.Posts.TimelinePost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_member_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ModeratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("moderated_at");

                    b.Property<int>("ReportCount")
                        .HasColumnType("integer")
                        .HasColumnName("report_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_timeline_posts");

                    b.HasIndex("TenantId", "AuthorMemberId")
                        .HasDatabaseName("ix_timeline_posts_tenant_id_author_member_id");

                    b.HasIndex("TenantId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_timeline_posts_tenant_id_status_created_at");

                    b.ToTable("timeline_posts", (string)null);
                });

            modelBuilder.Entity("Sangam.Timeline.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Sangam.Timeline.Domain.Posts.ModerationAction", b =>
                {
                    b.HasOne("Sangam.Timeline.Domain.Posts.TimelinePost", null)
                        .WithMany("ModerationActions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_moderation_actions_timeline_posts_post_id");
                });

            modelBuilder.Entity("Sangam.Timeline.Domain.Posts.PostComment", b =>
                {
                    b.HasOne("Sangam.Timeline.Domain.Posts.TimelinePost", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_comments_timeline_posts_post_id");
                });

            modelBuilder.Entity("Sangam.Timeline.Domain.Posts.PostReaction", b =>
                {
                    b.HasOne("Sangam.Timeline.Domain.Posts.TimelinePost", null)
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_reactions_timeline_posts_post_id");
                });

            modelBuilder.Entity("Sangam.Timeline.Domain.Posts.TimelinePost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ModerationActions");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
