// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sangam.MemberFamily.Infrastructure.Persistence;

#nullable disable

namespace Sangam.MemberFamily.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MemberFamilyDbContext))]
    [Migration("20260828125414_AddParentalConsent")]
    partial class AddParentalConsent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sangam.MemberFamily.Domain.Children.ChildConversionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_profile_id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("decision_note");

                    b.Property<string>("MobileOrEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("mobile_or_email");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_member_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_child_conversion_requests");

                    b.HasIndex("ChildProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_child_conversion_requests_child_profile_id")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_child_conversion_requests_tenant_id_status");

                    b.ToTable("child_conversion_requests", (string)null);
                });

            modelBuilder.Entity("Sangam.MemberFamily.Domain.Children.ChildProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConvertedMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_member_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("photo_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_child_profiles");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_child_profiles_family_id");

                    b.HasIndex("TenantId", "DateOfBirth")
                        .HasDatabaseName("ix_child_profiles_tenant_id_date_of_birth");

                    b.ToTable("child_profiles", (string)null);
                });

            modelBuilder.Entity("Sangam.MemberFamily.Domain.Families.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FamilyCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("family_code");

                    b.Property<Guid>("FamilyHeadMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_head_member_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_families");

                    b.HasIndex("TenantId", "FamilyCode")
                        .IsUnique()
                        .HasDatabaseName("ix_families_tenant_id_family_code");

                    b.ToTable("families", (string)null);
                });

            modelBuilder.Entity("Sangam.MemberFamily.Domain.Families.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("MemberProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_profile_id");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("relationship");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_family_members");

                    b.HasIndex("MemberProfileId")
                        .HasDatabaseName("ix_family_members_member_profile_id");

                    b.HasIndex("FamilyId", "MemberProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_family_members_family_id_member_profile_id");

                    b.ToTable("family_members", (string)null);
                });

            modelBuilder.Entity("Sangam.MemberFamily.Domain.Members.MemberProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<string>("Locality")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("locality");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mobile");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("photo_url");

                    b.Property<string>("Profession")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("profession");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_member_profiles");

                    b.HasIndex("TenantId", "FullName")
                        .HasDatabaseName("ix_member_profiles_tenant_id_full_name");

                    b.HasIndex("TenantId", "Locality")
                        .HasDatabaseName("ix_member_profiles_tenant_id_locality");

                    b.ToTable("member_profiles", (string)null);
                });

            modelBuilder.Entity("Sangam.MemberFamily.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Sangam.MemberFamily.Domain.Children.ChildConversionRequest", b =>
                {
                    b.HasOne("Sangam.MemberFamily.Domain.Children.ChildProfile", null)
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_child_conversion_requests_child_profiles_child_profile_id");
                });

            modelBuilder.Entity("Sangam.MemberFamily.Domain.Children.ChildProfile", b =>
                {
                    b.OwnsOne("Sangam.MemberFamily.Domain.Children.ParentalConsent", "ParentalConsent", b1 =>
                        {
                            b1.Property<Guid>("ChildProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Attestation")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("parental_consent_attestation");

                            b1.Property<DateTimeOffset>("GivenAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("parental_consent_given_at");

                            b1.Property<Guid>("GivenByMemberId")
                                .HasColumnType("uuid")
                                .HasColumnName("parental_consent_given_by");

                            b1.Property<string>("NoticeVersion")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("parental_consent_notice_version");

                            b1.HasKey("ChildProfileId");

                            b1.ToTable("child_profiles");

                            b1.WithOwner()
                                .HasForeignKey("ChildProfileId")
                                .HasConstraintName("fk_child_profiles_child_profiles_id");
                        });

                    b.Navigation("ParentalConsent");
                });

            modelBuilder.Entity("Sangam.MemberFamily.Domain.Families.FamilyMember", b =>
                {
                    b.HasOne("Sangam.MemberFamily.Domain.Families.Family", null)
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_members_families_family_id");
                });

            modelBuilder.Entity("Sangam.MemberFamily.Domain.Members.MemberProfile", b =>
                {
                    b.OwnsOne("Sangam.MemberFamily.Domain.Members.FieldPrivacy", "Privacy", b1 =>
                        {
                            b1.Property<Guid>("MemberProfileId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("privacy_address");

                            b1.Property<string>("DateOfBirth")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("privacy_date_of_birth");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("privacy_email");

                            b1.Property<string>("Mobile")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("privacy_mobile");

                            b1.Property<string>("Profession")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("privacy_profession");

                            b1.HasKey("MemberProfileId");

                            b1.ToTable("member_profiles");

                            b1.WithOwner()
                                .HasForeignKey("MemberProfileId")
                                .HasConstraintName("fk_member_profiles_member_profiles_id");
                        });

                    b.Navigation("Privacy")
                        .IsRequired();
                });

            modelBuilder.Entity("Sangam.MemberFamily.Domain.Families.Family", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
