// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sangam.Pathshala.Infrastructure.Persistence;

#nullable disable

namespace Sangam.Pathshala.Infrastructure.Migrations
{
    [DbContext(typeof(PathshalaDbContext))]
    partial class PathshalaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sangam.Pathshala.Domain.Enrolments.AttendanceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("ClassDate")
                        .HasColumnType("date")
                        .HasColumnName("class_date");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<Guid>("EnrolmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrolment_id");

                    b.Property<DateTimeOffset>("MarkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("marked_at");

                    b.Property<Guid>("MarkedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("marked_by_member_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_attendance");

                    b.HasIndex("ClassId", "ClassDate")
                        .HasDatabaseName("ix_attendance_class_id_class_date");

                    b.HasIndex("EnrolmentId", "ClassDate")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_enrolment_id_class_date");

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("Sangam.Pathshala.Domain.Enrolments.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateOnly>("ExamDate")
                        .HasColumnType("date")
                        .HasColumnName("exam_date");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer")
                        .HasColumnName("max_score");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_exams");

                    b.HasIndex("ClassId", "ExamDate")
                        .HasDatabaseName("ix_exams_class_id_exam_date");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("Sangam.Pathshala.Domain.Enrolments.ExamResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EnrolmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrolment_id");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<string>("Grade")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("grade");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RecordedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_member_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_exam_results");

                    b.HasIndex("EnrolmentId")
                        .HasDatabaseName("ix_exam_results_enrolment_id");

                    b.HasIndex("ExamId", "EnrolmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_results_exam_id_enrolment_id");

                    b.ToTable("exam_results", (string)null);
                });

            modelBuilder.Entity("Sangam.Pathshala.Domain.Enrolments.StudentEnrolment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_profile_id");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTimeOffset?>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<Guid>("PathshalaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pathshala_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_member_id");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("StudentUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id")
                        .HasName("pk_student_enrolments");

                    b.HasIndex("ChildProfileId")
                        .HasDatabaseName("ix_student_enrolments_child_profile_id");

                    b.HasIndex("RequestedByMemberId")
                        .HasDatabaseName("ix_student_enrolments_requested_by_member_id");

                    b.HasIndex("StudentUserId")
                        .HasDatabaseName("ix_student_enrolments_student_user_id");

                    b.HasIndex("ClassId", "Status")
                        .HasDatabaseName("ix_student_enrolments_class_id_status");

                    b.HasIndex("PathshalaId", "ChildProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_enrolments_pathshala_id_child_profile_id");

                    b.HasIndex("PathshalaId", "Status")
                        .HasDatabaseName("ix_student_enrolments_pathshala_id_status");

                    b.ToTable("student_enrolments", (string)null);
                });

            modelBuilder.Entity("Sangam.Pathshala.Domain.Pathshalas.AcademicSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label");

                    b.Property<Guid>("PathshalaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pathshala_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_academic_sessions");

                    b.HasIndex("PathshalaId", "Label")
                        .IsUnique()
                        .HasDatabaseName("ix_academic_sessions_pathshala_id_label");

                    b.ToTable("academic_sessions", (string)null);
                });

            modelBuilder.Entity("Sangam.Pathshala.Domain.Pathshalas.ClassSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_class_schedules");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_class_schedules_class_id");

                    b.ToTable("class_schedules", (string)null);
                });

            modelBuilder.Entity("Sangam.Pathshala.Domain.Pathshalas.Pathshala", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_person");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_pathshalas");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_pathshalas_tenant_id_status");

                    b.ToTable("pathshalas", (string)null);
                });

            modelBuilder.Entity("Sangam.Pathshala.Domain.Pathshalas.PathshalaClass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("PathshalaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pathshala_id");

                    b.Property<string>("RoomLabel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("room_label");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_classes");

                    b.HasIndex("PathshalaId")
                        .HasDatabaseName("ix_classes_pathshala_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_classes_session_id");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("Sangam.Pathshala.Domain.Pathshalas.TeacherAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<Guid>("TeacherMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_member_id");

                    b.HasKey("Id")
                        .HasName("pk_teacher_assignments");

                    b.HasIndex("ClassId", "TeacherMemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_teacher_assignments_class_id_teacher_member_id");

                    b.ToTable("teacher_assignments", (string)null);
                });

            modelBuilder.Entity("Sangam.Pathshala.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Sangam.Pathshala.Domain.Pathshalas.AcademicSession", b =>
                {
                    b.HasOne("Sangam.Pathshala.Domain.Pathshalas.Pathshala", null)
                        .WithMany("Sessions")
                        .HasForeignKey("PathshalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_academic_sessions_pathshalas_pathshala_id");
                });

            modelBuilder.Entity("Sangam.Pathshala.Domain.Pathshalas.ClassSchedule", b =>
                {
                    b.HasOne("Sangam.Pathshala.Domain.Pathshalas.PathshalaClass", null)
                        .WithMany("Schedule")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_schedules_classes_class_id");
                });

            modelBuilder.Entity("Sangam.Pathshala.Domain.Pathshalas.PathshalaClass", b =>
                {
                    b.HasOne("Sangam.Pathshala.Domain.Pathshalas.Pathshala", null)
                        .WithMany("Classes")
                        .HasForeignKey("PathshalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_classes_pathshalas_pathshala_id");
                });

            modelBuilder.Entity("Sangam.Pathshala.Domain.Pathshalas.TeacherAssignment", b =>
                {
                    b.HasOne("Sangam.Pathshala.Domain.Pathshalas.PathshalaClass", null)
                        .WithMany("Teachers")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_assignments_classes_class_id");
                });

            modelBuilder.Entity("Sangam.Pathshala.Domain.Pathshalas.Pathshala", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Sangam.Pathshala.Domain.Pathshalas.PathshalaClass", b =>
                {
                    b.Navigation("Schedule");

                    b.Navigation("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
