// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sangam.Boli.Infrastructure.Persistence;

#nullable disable

namespace Sangam.Boli.Infrastructure.Migrations
{
    [DbContext(typeof(BoliDbContext))]
    [Migration("20260901035304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sangam.Boli.Domain.Auctions.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<Guid>("BoliId")
                        .HasColumnType("uuid")
                        .HasColumnName("boli_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_bids");

                    b.HasIndex("BoliId", "Amount")
                        .IsUnique()
                        .HasDatabaseName("ix_bids_boli_id_amount");

                    b.HasIndex("BoliId", "PlacedAt")
                        .HasDatabaseName("ix_bids_boli_id_placed_at");

                    b.ToTable("bids", (string)null);
                });

            modelBuilder.Entity("Sangam.Boli.Domain.Auctions.Boli", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoliTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("boli_type_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EligibilityRule")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("eligibility_rule");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<long>("MinIncrement")
                        .HasColumnType("bigint")
                        .HasColumnName("min_increment");

                    b.Property<Guid>("OccasionId")
                        .HasColumnType("uuid")
                        .HasColumnName("occasion_id");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<long>("StartingAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("starting_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_boli");

                    b.HasIndex("OccasionId")
                        .HasDatabaseName("ix_boli_occasion_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_boli_tenant_id_status");

                    b.ToTable("boli", (string)null);
                });

            modelBuilder.Entity("Sangam.Boli.Domain.Auctions.BoliOccasion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("OccasionDate")
                        .HasColumnType("date")
                        .HasColumnName("occasion_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_boli_occasions");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_boli_occasions_tenant_id_status");

                    b.ToTable("boli_occasions", (string)null);
                });

            modelBuilder.Entity("Sangam.Boli.Domain.Auctions.BoliResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<Guid>("BoliId")
                        .HasColumnType("uuid")
                        .HasColumnName("boli_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WinningBidId")
                        .HasColumnType("uuid")
                        .HasColumnName("winning_bid_id");

                    b.Property<Guid>("WinningMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("winning_member_id");

                    b.HasKey("Id")
                        .HasName("pk_boli_results");

                    b.HasIndex("BoliId")
                        .IsUnique()
                        .HasDatabaseName("ix_boli_results_boli_id");

                    b.HasIndex("TenantId", "PublishedAt")
                        .HasDatabaseName("ix_boli_results_tenant_id_published_at");

                    b.ToTable("boli_results", (string)null);
                });

            modelBuilder.Entity("Sangam.Boli.Domain.Auctions.BoliType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OccasionId")
                        .HasColumnType("uuid")
                        .HasColumnName("occasion_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_boli_types");

                    b.HasIndex("OccasionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_boli_types_occasion_id_name");

                    b.ToTable("boli_types", (string)null);
                });

            modelBuilder.Entity("Sangam.Boli.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Sangam.Boli.Domain.Auctions.BoliType", b =>
                {
                    b.HasOne("Sangam.Boli.Domain.Auctions.BoliOccasion", null)
                        .WithMany("Types")
                        .HasForeignKey("OccasionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_boli_types_boli_occasions_occasion_id");
                });

            modelBuilder.Entity("Sangam.Boli.Domain.Auctions.BoliOccasion", b =>
                {
                    b.Navigation("Types");
                });
#pragma warning restore 612, 618
        }
    }
}
