// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sangam.CelebrityVoting.Infrastructure.Persistence;

#nullable disable

namespace Sangam.CelebrityVoting.Infrastructure.Migrations
{
    [DbContext(typeof(CelebrityVotingDbContext))]
    partial class CelebrityVotingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sangam.CelebrityVoting.Domain.Campaigns.CampaignResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("PublishedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by");

                    b.Property<string>("RankedCandidateIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ranked_candidate_ids");

                    b.HasKey("Id")
                        .HasName("pk_campaign_results");

                    b.HasIndex("CampaignId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_results_campaign_id");

                    b.ToTable("campaign_results", (string)null);
                });

            modelBuilder.Entity("Sangam.CelebrityVoting.Domain.Campaigns.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTimeOffset>("NominatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("nominated_at");

                    b.Property<Guid>("NominatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("nominated_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("VotingCampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("voting_campaign_id");

                    b.HasKey("Id")
                        .HasName("pk_candidates");

                    b.HasIndex("VotingCampaignId")
                        .HasDatabaseName("ix_candidates_voting_campaign_id");

                    b.HasIndex("CampaignId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_candidates_campaign_id_member_id");

                    b.ToTable("candidates", (string)null);
                });

            modelBuilder.Entity("Sangam.CelebrityVoting.Domain.Campaigns.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("VoterMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("voter_member_id");

                    b.HasKey("Id")
                        .HasName("pk_votes");

                    b.HasIndex("CampaignId", "CandidateId")
                        .HasDatabaseName("ix_votes_campaign_id_candidate_id");

                    b.HasIndex("CampaignId", "VoterMemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_votes_campaign_id_voter_member_id");

                    b.ToTable("votes", (string)null);
                });

            modelBuilder.Entity("Sangam.CelebrityVoting.Domain.Campaigns.VotingCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("NominationEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("nomination_end_at");

                    b.Property<DateTimeOffset>("NominationStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("nomination_start_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("ResultsVisibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("results_visibility");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("TopN")
                        .HasColumnType("integer")
                        .HasColumnName("top_n");

                    b.Property<DateTimeOffset>("VotingEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voting_end_at");

                    b.Property<DateTimeOffset>("VotingStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voting_start_at");

                    b.HasKey("Id")
                        .HasName("pk_voting_campaigns");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_voting_campaigns_tenant_id_status");

                    b.ToTable("voting_campaigns", (string)null);
                });

            modelBuilder.Entity("Sangam.CelebrityVoting.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("topic");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Sangam.CelebrityVoting.Domain.Campaigns.Candidate", b =>
                {
                    b.HasOne("Sangam.CelebrityVoting.Domain.Campaigns.VotingCampaign", null)
                        .WithMany("Candidates")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidates_voting_campaigns_campaign_id");

                    b.HasOne("Sangam.CelebrityVoting.Domain.Campaigns.VotingCampaign", null)
                        .WithMany("Ballot")
                        .HasForeignKey("VotingCampaignId")
                        .HasConstraintName("fk_candidates_campaigns_voting_campaign_id");
                });

            modelBuilder.Entity("Sangam.CelebrityVoting.Domain.Campaigns.VotingCampaign", b =>
                {
                    b.Navigation("Ballot");

                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
